channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-catalyst=1.10
  - r::r-stringr
  - r-ggpmisc
  - r-data.table
  - r-dtplyr
  - r-ggplot2
  - bioconductor-flowcore
  - r-tiff
  - r::rstudio
  - r-plotly
  - r-matrixstats
  - r-reshape2
  - r-raster
  - r-viridis
  - bioconductor-ebimage
  - r-scales
  - r-fields
  - plotly
  - r-irkernel
  - libiconv
  - icu<=60
  - libgfortran
  - r-devtools
