---
title: "Adapt spillover matrix for IMC compensation"
author: 'Vito Zanotelli et al.'
output:
  html_document:
    df_print: paged
    keep_md: true
---

# Adapts the spillover matrix for use in CellProfiller

```{r Libraries}
library(CATALYST)
```


##
```{r Setup}
fn_sm = '../data/Figure_S5/paper_version_Spillover_Matrix_2_sm.csv'
# a csv with a list of metals used, generated from the IMC preprocessing ipython notebook:
fn_imc_metals = '../data/Figure_4/IMC_image/analysis/imc_example_image_a0_full.csv'
fol_out = dirname(fn_imc_metals)
prefix_out =  'adapted_'
```


Write the spillover matrix for cellprofier

```{r}
sm = read.csv(fn_sm, row.names = 1)
analysis_channels = read.csv(fn_imc_metals,header = F)
analysis_channels = paste(as.character(analysis_channels$V1), 'Di', sep = '')
sm_table = CATALYST::adaptSpillmat(input_sm = as.matrix(sm), out_chs = analysis_channels)
```

Writes out a 32bit tiff that can be used in CellProfiller together with the "CorrectSpilloverApply" module
```{r}
tiff::writeTIFF(sm_table, file.path(fol_out, 'imc_full_sm.tiff'), bits.per.sample = 32, reduce = T)
```

```{r}
sessionInfo()
```